using System.Collections.Immutable;

namespace Helper.Constants;

public static class StaCsvConfigTemplate
{
    public static readonly ImmutableList<ConfigObject> PtInfSubConfig = new List<ConfigObject>()
    {
        new ConfigObject(false, "カナ氏名", "KanaName"),
        new ConfigObject(false, "性別", "Sex"),
        new ConfigObject(false, "生年月日(西暦)", "Birthday"),
        new ConfigObject(false, "生年月日(和暦)", "BirthdayW"),
        new ConfigObject(false, "生年月日(和暦西暦)", "BirthdayWS"),
        new ConfigObject(false, "年齢", "Age"),
        new ConfigObject(false, "死亡日", "DeathDate"),
        new ConfigObject(false, "郵便番号", "HomePost"),
        new ConfigObject(false, "住所", "HomeAddress"),
        new ConfigObject(false, "住所１", "HomeAddress1"),
        new ConfigObject(false, "住所２", "HomeAddress2"),
        new ConfigObject(false, "電話番号", "Tel"),
        new ConfigObject(false, "電話番号１", "Tel1"),
        new ConfigObject(false, "電話番号２", "Tel2"),
        new ConfigObject(false, "メールアドレス", "Mail"),
        new ConfigObject(false, "世帯主名", "Setainusi"),
        new ConfigObject(false, "世帯主との続柄", "Zokugara"),
        new ConfigObject(false, "職業", "Job"),
        new ConfigObject(false, "連絡先名称", "RenrakuName"),
        new ConfigObject(false, "連絡先郵便番号", "RenrakuPost"),
        new ConfigObject(false, "連絡先住所１", "RenrakuAddress1"),
        new ConfigObject(false, "連絡先住所２", "RenrakuAddress2"),
        new ConfigObject(false, "連絡先電話番号", "RenrakuTel"),
        new ConfigObject(false, "連絡先備考", "RenrakuMemo"),
        new ConfigObject(false, "勤務先名称", "OfficeName"),
        new ConfigObject(false, "勤務先郵便番号", "OfficePost"),
        new ConfigObject(false, "勤務先住所１", "OfficeAddress1"),
        new ConfigObject(false, "勤務先住所２", "OfficeAddress2"),
        new ConfigObject(false, "勤務先電話番号", "OfficeTel"),
        new ConfigObject(false, "勤務先備考", "OfficeMemo"),
        new ConfigObject(false, "領収書明細", "IsRyosyuDetail"),
        new ConfigObject(false, "主治医", "PrimaryDoctor"),
        new ConfigObject(false, "テスト患者区分", "IsTester"),
        new ConfigObject(false, "患者登録日時", "CreateDate"),
        new ConfigObject(false, "最終来院日", "LastVisitDate"),
        new ConfigObject(false, "患者コメント", "PtCmt"),
        new ConfigObject(false, "調整額", "AdjFutan"),
        new ConfigObject(false, "調整率", "AdjRate"),
        new ConfigObject(false, "自動算定", "AutoSantei"),
    }.ToImmutableList();

    /// <summary>
    /// 患者情報
    /// </summary>
    public static readonly ImmutableList<ConfigObject> PtInfConfig = new List<ConfigObject>()
    {
        new ConfigObject(true, "患者番号", "PtNum"),
        new ConfigObject(true, "氏名", "PtName"),
        new ConfigObject(true, "カナ氏名", "KanaName"),
        new ConfigObject(true, "性別", "Sex"),
        new ConfigObject(false, "生年月日(西暦)", "Birthday"),
        new ConfigObject(false, "生年月日(和暦)", "BirthdayW"),
        new ConfigObject(true, "生年月日(和暦西暦)", "BirthdayWS"),
        new ConfigObject(true, "年齢", "Age"),
        new ConfigObject(false, "年齢（月）", "AgeMonth"),
        new ConfigObject(false, "死亡日", "DeathDate"),
        new ConfigObject(true, "郵便番号", "HomePost"),
        new ConfigObject(true, "住所", "HomeAddress"),
        new ConfigObject(false, "住所１", "HomeAddress1"),
        new ConfigObject(false, "住所２", "HomeAddress2"),
        new ConfigObject(true, "電話番号", "Tel"),
        new ConfigObject(false, "電話番号１", "Tel1"),
        new ConfigObject(false, "電話番号２", "Tel2"),
        new ConfigObject(false, "メールアドレス", "Mail"),
        new ConfigObject(false, "世帯主名", "Setainusi"),
        new ConfigObject(false, "世帯主との続柄", "Zokugara"),
        new ConfigObject(false, "職業", "Job"),
        new ConfigObject(false, "連絡先名称", "RenrakuName"),
        new ConfigObject(false, "連絡先郵便番号", "RenrakuPost"),
        new ConfigObject(false, "連絡先住所１", "RenrakuAddress1"),
        new ConfigObject(false, "連絡先住所２", "RenrakuAddress2"),
        new ConfigObject(false, "連絡先電話番号", "RenrakuTel"),
        new ConfigObject(false, "連絡先備考", "RenrakuMemo"),
        new ConfigObject(false, "勤務先名称", "OfficeName"),
        new ConfigObject(false, "勤務先郵便番号", "OfficePost"),
        new ConfigObject(false, "勤務先住所１", "OfficeAddress1"),
        new ConfigObject(false, "勤務先住所２", "OfficeAddress2"),
        new ConfigObject(false, "勤務先電話番号", "OfficeTel"),
        new ConfigObject(false, "勤務先備考", "OfficeMemo"),
        new ConfigObject(false, "領収書明細", "IsRyosyuDetail"),
        new ConfigObject(false, "主治医", "PrimaryDoctor"),
        new ConfigObject(false, "テスト患者区分", "IsTester"),
        new ConfigObject(false, "患者登録日時", "CreateDate"),
        new ConfigObject(false, "初回来院日", "FirstVisitDate"),
        new ConfigObject(true, "最終来院日", "LastVisitDate"),
        new ConfigObject(false, "患者コメント", "PtCmt"),
        new ConfigObject(false, "調整額", "AdjFutan"),
        new ConfigObject(false, "調整率", "AdjRate"),
        new ConfigObject(false, "自動算定", "AutoSantei"),
    }.ToImmutableList();

    /// <summary>
    /// 保険情報
    /// </summary>
    public static readonly ImmutableList<ConfigObject> HokenInfConfig = new List<ConfigObject>()
    {
        new ConfigObject(true, "患者番号", "PtNum"),
        new ConfigObject(true, "氏名", "PtName"),
        new ConfigObject(true, "保険組合せID", "HokenPid"),
        new ConfigObject(true, "保険区分", "HokenKbn"),
        new ConfigObject(true, "保険区分名称", "HokenKbnName"),
        new ConfigObject(true, "保険種別コード", "HokenSbtCd"),
        new ConfigObject(true, "保険種別コード名称", "HokenSbtCdName"),
        new ConfigObject(true, "保険メモ", "HokenMemo"),
        new ConfigObject(true, "適用開始日", "StartDate"),
        new ConfigObject(true, "適用終了日", "EndDate"),
        new ConfigObject(true, "保険ID", "HokenId"),
        new ConfigObject(false, "保険番号", "HokenNo"),
        new ConfigObject(false, "保険番号枝番", "HokenEdaNo"),
        new ConfigObject(true, "保険者番号", "HokensyaNo"),
        new ConfigObject(true, "記号", "Kigo"),
        new ConfigObject(true, "番号", "Bango"),
        new ConfigObject(true, "枝番", "EdaNo"),
        new ConfigObject(true, "本人家族区分", "HonkeKbn"),
        new ConfigObject(true, "法別番号", "Houbetu"),
        new ConfigObject(false, "被保険者名", "HokensyaName"),
        new ConfigObject(false, "被保険者郵便番号", "HokensyaPost"),
        new ConfigObject(false, "被保険者住所", "HokensyaAddress"),
        new ConfigObject(false, "被保険者電話番号", "HokensyaTel"),
        new ConfigObject(false, "継続区分", "KeizokuKbn"),
        new ConfigObject(true, "資格取得日", "SikakuDate"),
        new ConfigObject(true, "交付日", "KofuDate"),
        new ConfigObject(true, "高額療養費区分", "KogakuKbn"),
        new ConfigObject(false, "高額療養費処理区分", "KogakuType"),
        new ConfigObject(false, "限度額特例対象年月１", "TokureiYm1"),
        new ConfigObject(false, "限度額特例対象年月２", "TokureiYm2"),
        new ConfigObject(false, "多数回該当適用開始年月", "TasukaiYm"),
        new ConfigObject(true, "職務上区分", "SyokumuKbn"),
        new ConfigObject(true, "国保減免区分", "GenmenKbn"),
        new ConfigObject(true, "国保減免割合", "GenmenRate"),
        new ConfigObject(true, "国保減免金額", "GenmenGaku"),
        new ConfigObject(true, "特記事項１", "Tokki1"),
        new ConfigObject(true, "特記事項２", "Tokki2"),
        new ConfigObject(true, "特記事項３", "Tokki3"),
        new ConfigObject(true, "特記事項４", "Tokki4"),
        new ConfigObject(true, "特記事項５", "Tokki5"),
        new ConfigObject(true, "労災交付番号", "RousaiKofuNo"),
        new ConfigObject(true, "労災災害区分", "RousaiSaigaiKbn"),
        new ConfigObject(true, "労災事業所名", "RousaiJigyosyoName"),
        new ConfigObject(true, "労災都道府県名", "RousaiPrefName"),
        new ConfigObject(true, "労災所在地郡市区名", "RousaiCityName"),
        new ConfigObject(true, "労災傷病年月日", "RousaiSyobyoDate"),
        new ConfigObject(true, "労災傷病コード", "RousaiSyobyoCd"),
        new ConfigObject(true, "労災労働局コード", "RousaiRoudouCd"),
        new ConfigObject(true, "労災監督署コード", "RousaiKantokuCd"),
        new ConfigObject(true, "労災レセ請求回数", "RousaiReceCount"),
        new ConfigObject(true, "労災療養開始日", "RyoyoStartDate"),
        new ConfigObject(true, "労災療養終了日", "RyoyoEndDate"),
        new ConfigObject(true, "自賠保険会社名", "JibaiHokenName"),
        new ConfigObject(true, "自賠保険担当者", "JibaiHokenTanto"),
        new ConfigObject(true, "自賠保険連絡先", "JibaiHokenTel"),
        new ConfigObject(true, "自賠受傷日", "JibaiJyusyouDate"),
        new ConfigObject(true, "公費１ID", "Kohi1Id"),
        new ConfigObject(false, "公費１都道府県番号", "Kohi1PrefNo"),
        new ConfigObject(false, "公費１保険番号", "Kohi1HokenNo"),
        new ConfigObject(false, "公費１保険番号枝番", "Kohi1HokenEdaNo"),
        new ConfigObject(true, "公費１負担者番号", "Kohi1FutansyaNo"),
        new ConfigObject(true, "公費１受給者番号", "Kohi1JyukyusyaNo"),
        new ConfigObject(true, "公費１特殊受給者番号", "Kohi1TokusyuNo"),
        new ConfigObject(true, "公費１資格取得日", "Kohi1SikakuDate"),
        new ConfigObject(true, "公費１交付日", "Kohi1KofuDate"),
        new ConfigObject(true, "公費１適用開始日", "Kohi1StartDate"),
        new ConfigObject(true, "公費１適用終了日", "Kohi1EndDate"),
        new ConfigObject(false, "公費１負担率", "Kohi1Rate"),
        new ConfigObject(false, "公費１一部負担限度額", "Kohi1GendoGaku"),
        new ConfigObject(true, "公費２ID", "Kohi2Id"),
        new ConfigObject(false, "公費２都道府県番号", "Kohi2PrefNo"),
        new ConfigObject(false, "公費２保険番号", "Kohi2HokenNo"),
        new ConfigObject(false, "公費２保険番号枝番", "Kohi2HokenEdaNo"),
        new ConfigObject(true, "公費２負担者番号", "Kohi2FutansyaNo"),
        new ConfigObject(true, "公費２受給者番号", "Kohi2JyukyusyaNo"),
        new ConfigObject(true, "公費２特殊受給者番号", "Kohi2TokusyuNo"),
        new ConfigObject(true, "公費２資格取得日", "Kohi2SikakuDate"),
        new ConfigObject(true, "公費２交付日", "Kohi2KofuDate"),
        new ConfigObject(true, "公費２適用開始日", "Kohi2StartDate"),
        new ConfigObject(true, "公費２適用終了日", "Kohi2EndDate"),
        new ConfigObject(false, "公費２負担率", "Kohi2Rate"),
        new ConfigObject(false, "公費２一部負担限度額", "Kohi2GendoGaku"),
        new ConfigObject(true, "公費３ID", "Kohi3Id"),
        new ConfigObject(false, "公費３都道府県番号", "Kohi3PrefNo"),
        new ConfigObject(false, "公費３保険番号", "Kohi3HokenNo"),
        new ConfigObject(false, "公費３保険番号枝番", "Kohi3HokenEdaNo"),
        new ConfigObject(true, "公費３負担者番号", "Kohi3FutansyaNo"),
        new ConfigObject(true, "公費３受給者番号", "Kohi3JyukyusyaNo"),
        new ConfigObject(true, "公費３特殊受給者番号", "Kohi3TokusyuNo"),
        new ConfigObject(true, "公費３資格取得日", "Kohi3SikakuDate"),
        new ConfigObject(true, "公費３交付日", "Kohi3KofuDate"),
        new ConfigObject(true, "公費３適用開始日", "Kohi3StartDate"),
        new ConfigObject(true, "公費３適用終了日", "Kohi3EndDate"),
        new ConfigObject(false, "公費３負担率", "Kohi3Rate"),
        new ConfigObject(false, "公費３一部負担限度額", "Kohi3GendoGaku"),
        new ConfigObject(true, "公費４ID", "Kohi4Id"),
        new ConfigObject(false, "公費４都道府県番号", "Kohi4PrefNo"),
        new ConfigObject(false, "公費４保険番号", "Kohi4HokenNo"),
        new ConfigObject(false, "公費４保険番号枝番", "Kohi4HokenEdaNo"),
        new ConfigObject(true, "公費４負担者番号", "Kohi4FutansyaNo"),
        new ConfigObject(true, "公費４受給者番号", "Kohi4JyukyusyaNo"),
        new ConfigObject(true, "公費４特殊受給者番号", "Kohi4TokusyuNo"),
        new ConfigObject(true, "公費４資格取得日", "Kohi4SikakuDate"),
        new ConfigObject(true, "公費４交付日", "Kohi4KofuDate"),
        new ConfigObject(true, "公費４適用開始日", "Kohi4StartDate"),
        new ConfigObject(true, "公費４適用終了日", "Kohi4EndDate"),
        new ConfigObject(false, "公費４負担率", "Kohi4Rate"),
        new ConfigObject(false, "公費４一部負担限度額", "Kohi4GendoGaku"),
    }.ToImmutableList();

    /// <summary>
    /// 病名情報
    /// </summary>
    public static readonly ImmutableList<ConfigObject> ByomeiInfConfig = new List<ConfigObject>()
    {
        new ConfigObject(true, "患者番号", "PtNum"),
        new ConfigObject(true, "氏名", "PtName"),
        new ConfigObject(false, "基本病名コード", "ByomeiCd"),
        new ConfigObject(false, "修飾語コード１", "SyusyokuCd1"),
        new ConfigObject(false, "修飾語コード２", "SyusyokuCd2"),
        new ConfigObject(false, "修飾語コード３", "SyusyokuCd3"),
        new ConfigObject(false, "修飾語コード４", "SyusyokuCd4"),
        new ConfigObject(false, "修飾語コード５", "SyusyokuCd5"),
        new ConfigObject(false, "修飾語コード６", "SyusyokuCd6"),
        new ConfigObject(false, "修飾語コード７", "SyusyokuCd7"),
        new ConfigObject(false, "修飾語コード８", "SyusyokuCd8"),
        new ConfigObject(false, "修飾語コード９", "SyusyokuCd9"),
        new ConfigObject(false, "修飾語コード１０", "SyusyokuCd10"),
        new ConfigObject(false, "修飾語コード１１", "SyusyokuCd11"),
        new ConfigObject(false, "修飾語コード１２", "SyusyokuCd12"),
        new ConfigObject(false, "修飾語コード１３", "SyusyokuCd13"),
        new ConfigObject(false, "修飾語コード１４", "SyusyokuCd14"),
        new ConfigObject(false, "修飾語コード１５", "SyusyokuCd15"),
        new ConfigObject(false, "修飾語コード１６", "SyusyokuCd16"),
        new ConfigObject(false, "修飾語コード１７", "SyusyokuCd17"),
        new ConfigObject(false, "修飾語コード１８", "SyusyokuCd18"),
        new ConfigObject(false, "修飾語コード１９", "SyusyokuCd19"),
        new ConfigObject(false, "修飾語コード２０", "SyusyokuCd20"),
        new ConfigObject(false, "修飾語コード２１", "SyusyokuCd21"),
        new ConfigObject(true, "病名", "Byomei"),
        new ConfigObject(true, "開始日", "StartDate"),
        new ConfigObject(true, "転帰区分", "TenkiKbn"),
        new ConfigObject(true, "転帰日", "TenkiDate"),
        new ConfigObject(true, "主病名区分", "SyubyoKbn"),
        new ConfigObject(false, "慢性疾患区分", "SikkanKbn"),
        new ConfigObject(true, "慢性疾患区分名称", "SikkanKbnName"),
        new ConfigObject(false, "難病外来コード", "NanbyoCd"),
        new ConfigObject(true, "補足コメント", "HosokuCmt"),
        new ConfigObject(true, "保険レセプトID", "HokenRid"),
        new ConfigObject(false, "当月病名区分", "TogetuByomei"),
        new ConfigObject(false, "レセプト非表示区分", "IsNodspRece"),
        new ConfigObject(false, "カルテ非表示区分", "IsNodspKarte"),
    }.ToImmutableList();

    /// <summary>
    /// 来院情報
    /// </summary>
    public static readonly ImmutableList<ConfigObject> RaiinInfConfig = new List<ConfigObject>()
    {
        new ConfigObject(true, "患者番号", "PtNum"),
        new ConfigObject(true, "氏名", "PtName"),
        new ConfigObject(false, "年齢（月）", "AgeMonth"),
        new ConfigObject(true, "診療日", "SinDate"),
        new ConfigObject(false, "来院番号", "RaiinNo"),
        new ConfigObject(false, "親来院番号", "OyaRaiinNo"),
        new ConfigObject(true, "状態", "Status"),
        new ConfigObject(false, "予約フラグ", "IsYoyaku"),
        new ConfigObject(true, "予約時間", "YoyakuTime"),
        new ConfigObject(false, "予約者ID", "YoyakuId"),
        new ConfigObject(false, "受付種別", "UketukeSbt"),
        new ConfigObject(true, "受付時間", "UketukeTime"),
        new ConfigObject(false, "受付者ID", "UketukeId"),
        new ConfigObject(true, "受付番号", "UketukeNo"),
        new ConfigObject(true, "診察開始時間", "SinStartTime"),
        new ConfigObject(false, "診察終了時間", "SinEndTime"),
        new ConfigObject(true, "精算時間", "KaikeiTime"),
        new ConfigObject(false, "精算者ID", "KaikeiId"),
        new ConfigObject(true, "診療科", "KaName"),
        new ConfigObject(true, "担当医ID", "TantoId"),
        new ConfigObject(false, "担当医", "TantoName"),
        new ConfigObject(false, "保険組合せID", "HokenPid"),
        new ConfigObject(true, "初再診区分", "SyosaisinKbn"),
        new ConfigObject(false, "初再診区分略称", "SyosaisinKbnS"),
        new ConfigObject(true, "時間枠区分", "JikanKbn"),
        new ConfigObject(false, "来院コメント", "RaiinCmt"),
        new ConfigObject(false, "来院備考", "RaiinBiko"),
        new ConfigObject(false, "初回来院日フラグ", "IsFirstVisitDate"),
        new ConfigObject(false, "初回来院日", "FirstVisitDate"),
    }.ToImmutableList();

    /// <summary>
    /// 診療情報（オーダー）
    /// </summary>
    public static readonly ImmutableList<ConfigObject> MedicalInfOrderConfig = new List<ConfigObject>()
    {
        new ConfigObject(true, "患者番号", "PtNum"),
        new ConfigObject(true, "氏名", "PtName"),
        new ConfigObject(true, "診療日", "SinDate"),
        new ConfigObject(true, "来院番号", "RaiinNo"),
        new ConfigObject(false, "親来院番号", "OyaRaiinNo"),
        new ConfigObject(true, "状態", "Status"),
        new ConfigObject(false, "受付種別", "UketukeSbt"),
        new ConfigObject(false, "診療科", "KaName"),
        new ConfigObject(false, "担当医ID", "TantoId"),
        new ConfigObject(false, "担当医", "TantoName"),
        new ConfigObject(false, "受付番号", "UketukeNo"),
        new ConfigObject(true, "並び順", "SortNo"),
        new ConfigObject(true, "剤番号", "RpNo"),
        new ConfigObject(true, "剤枝番", "RpEdaNo"),
        new ConfigObject(true, "保険組合せID", "HokenPid"),
        new ConfigObject(false, "保険組合せ名称", "HokenPname"),
        new ConfigObject(true, "オーダー行為区分", "OdrKouiKbn"),
        new ConfigObject(true, "剤名称", "RpName"),
        new ConfigObject(true, "院内院外区分", "InoutKbn"),
        new ConfigObject(true, "至急区分", "SikyuKbn"),
        new ConfigObject(true, "処方種別", "SyohoSbt"),
        new ConfigObject(true, "算定区分", "SanteiKbn"),
        new ConfigObject(true, "透析区分", "TosekiKbn"),
        new ConfigObject(true, "日数回数", "DaysCnt"),
        new ConfigObject(true, "行番号", "RowNo"),
        new ConfigObject(true, "診療行為区分", "SinKouiKbn"),
        new ConfigObject(true, "診療行為コード", "ItemCd"),
        new ConfigObject(true, "診療行為名称", "ItemName"),
        new ConfigObject(true, "数量", "Suryo"),
        new ConfigObject(true, "単位名称", "UnitName"),
        new ConfigObject(false, "単位種別", "UnitSBT"),
        new ConfigObject(false, "単位換算値", "TermVal"),
        new ConfigObject(true, "後発医薬品区分", "KohatuKbn"),
        new ConfigObject(true, "処方せん記載区分", "SyohoKbn"),
        new ConfigObject(true, "処方せん記載制限区分", "SyohoLimitKbn"),
        new ConfigObject(false, "薬剤区分", "DrugKbn"),
        new ConfigObject(false, "用法区分", "YohoKbn"),
        new ConfigObject(false, "告示等識別区分（１）", "Kokuji1"),
        new ConfigObject(false, "告示等識別区分（２）", "Kokuji2"),
        new ConfigObject(true, "レセ非表示区分", "IsNodspRece"),
        new ConfigObject(false, "一般名コード", "IpnCd"),
        new ConfigObject(false, "一般名", "IpnName"),
        new ConfigObject(false, "実施区分", "JissiKbn"),
        new ConfigObject(false, "実施日時", "JissiDate"),
        new ConfigObject(false, "実施者", "JissiId"),
        new ConfigObject(false, "実施端末", "JissiMachine"),
        new ConfigObject(false, "検査依頼コード", "ReqCd"),
        new ConfigObject(false, "分割調剤", "Bunkatu"),
        new ConfigObject(false, "コメント名称", "CmtName"),
        new ConfigObject(false, "コメント文", "CmtOpt"),
        new ConfigObject(false, "文字色", "FontColor"),
    }.ToImmutableList();

    /// <summary>
    /// 診療情報（算定）
    /// </summary>
    public static readonly ImmutableList<ConfigObject> MedicalInfCalConfig = new List<ConfigObject>()
    {
        new ConfigObject(true, "患者番号", "PtNum"),
        new ConfigObject(true, "氏名", "PtName"),
        new ConfigObject(true, "診療日", "SinDate"),
        new ConfigObject(true, "来院番号", "RaiinNo"),
        new ConfigObject(false, "親来院番号", "OyaRaiinNo"),
        new ConfigObject(false, "状態", "Status"),
        new ConfigObject(false, "受付種別", "UketukeSbt"),
        new ConfigObject(false, "診療科", "KaName"),
        new ConfigObject(false, "担当医ID", "TantoId"),
        new ConfigObject(false, "担当医", "TantoName"),
        new ConfigObject(false, "受付番号", "UketukeNo"),
        new ConfigObject(true, "診療識別", "SinId"),
        new ConfigObject(true, "剤番号", "RpNo"),
        new ConfigObject(true, "連番", "SeqNo"),
        new ConfigObject(true, "行番号", "RowNo"),
        new ConfigObject(true, "算定区分", "SanteiKbn"),
        new ConfigObject(true, "保険組合せID", "HokenPid"),
        new ConfigObject(true, "保険ID", "HokenId"),
        new ConfigObject(true, "点数小計", "SubTotalTen"),
        new ConfigObject(true, "内税小計", "SubTotalZei"),
        new ConfigObject(true, "回数小計", "SubTotalCount"),
        new ConfigObject(true, "診療行為コード", "ItemCd"),
        new ConfigObject(true, "オーダー診療行為コード", "OdrItemCd"),
        new ConfigObject(true, "診療行為名称", "ItemName"),
        new ConfigObject(true, "数量", "Suryo"),
        new ConfigObject(true, "単位名称", "UnitName"),
        new ConfigObject(true, "点数", "Ten"),
        new ConfigObject(true, "内税", "Zei"),
        new ConfigObject(true, "レセ非表示区分", "IsNodspRece"),
        new ConfigObject(true, "紙レセ非表示区分", "IsNodspPaperRece"),
        new ConfigObject(true, "領収証非表示区分", "IsNodspRyosyu"),
        new ConfigObject(true, "院外処方区分", "InoutKbn"),
        new ConfigObject(true, "円点区分", "EntenKbn"),
        new ConfigObject(true, "自費種別", "JihiSbt"),
        new ConfigObject(true, "課税区分", "KazeiKbn"),
    }.ToImmutableList();

    /// <summary>
    /// カルテ情報
    /// </summary>
    public static readonly ImmutableList<ConfigObject> MedicalRecordInfConfig = new List<ConfigObject>()
    {
        new ConfigObject(true, "患者番号", "PtNum"),
        new ConfigObject(true, "氏名", "PtName"),
        new ConfigObject(true, "診療日", "SinDate"),
        new ConfigObject(true, "来院番号", "RaiinNo"),
        new ConfigObject(false, "親来院番号", "OyaRaiinNo"),
        new ConfigObject(false, "状態", "Status"),
        new ConfigObject(false, "受付種別", "UketukeSbt"),
        new ConfigObject(false, "診療科", "KaName"),
        new ConfigObject(false, "担当医ID", "TantoId"),
        new ConfigObject(false, "担当医", "TantoName"),
        new ConfigObject(false, "受付番号", "UketukeNo"),
        new ConfigObject(true, "カルテ区分", "KarteKbn"),
        new ConfigObject(true, "テキスト", "Text"),
    }.ToImmutableList();

    /// <summary>
    /// 検査情報
    /// </summary>
    public static readonly ImmutableList<ConfigObject> KensaInfConfig = new List<ConfigObject>()
    {
        new ConfigObject(true, "患者番号", "PtNum"),
        new ConfigObject(true, "氏名", "PtName"),
        new ConfigObject(true, "依頼日", "IraiDate"),
        new ConfigObject(true, "センターコード", "CenterCd"),
        new ConfigObject(true, "検査項目コード", "KensaItemCd"),
        new ConfigObject(true, "検査項目名称", "KensaName"),
        new ConfigObject(true, "結果値", "ResultValue"),
        new ConfigObject(true, "単位名称", "UnitName"),
        new ConfigObject(true, "基準値", "StandardVal"),
        new ConfigObject(true, "異常値区分", "AbnormalKbn"),
    }.ToImmutableList();

}

public class ConfigObject
{
    public ConfigObject(bool isSelected, string outputColumnName, string saveName)
    {
        IsSelected = isSelected;
        OutputColumnName = outputColumnName;
        SaveName = saveName;
    }

    public bool IsSelected { get; private set; }

    public string OutputColumnName { get; private set; }

    public string SaveName { get; private set; }
}
