using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Helper.Constants
{
    public class StaCsvConfigTemplate
    {
        public static List<(bool isSelected, string outputColumnName, string saveName)> PtInfSubConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (false, "カナ氏名", "KanaName"),
            (false, "性別", "Sex"),
            (false, "生年月日(西暦)", "Birthday"),
            (false, "生年月日(和暦)", "BirthdayW"),
            (false, "生年月日(和暦西暦)", "BirthdayWS"),
            (false, "年齢", "Age"),
            (false, "死亡日", "DeathDate"),
            (false, "郵便番号", "HomePost"),
            (false, "住所", "HomeAddress"),
            (false, "住所１", "HomeAddress1"),
            (false, "住所２", "HomeAddress2"),
            (false, "電話番号", "Tel"),
            (false, "電話番号１", "Tel1"),
            (false, "電話番号２", "Tel2"),
            (false, "メールアドレス", "Mail"),
            (false, "世帯主名", "Setainusi"),
            (false, "世帯主との続柄", "Zokugara"),
            (false, "職業", "Job"),
            (false, "連絡先名称", "RenrakuName"),
            (false, "連絡先郵便番号", "RenrakuPost"),
            (false, "連絡先住所１", "RenrakuAddress1"),
            (false, "連絡先住所２", "RenrakuAddress2"),
            (false, "連絡先電話番号", "RenrakuTel"),
            (false, "連絡先備考", "RenrakuMemo"),
            (false, "勤務先名称", "OfficeName"),
            (false, "勤務先郵便番号", "OfficePost"),
            (false, "勤務先住所１", "OfficeAddress1"),
            (false, "勤務先住所２", "OfficeAddress2"),
            (false, "勤務先電話番号", "OfficeTel"),
            (false, "勤務先備考", "OfficeMemo"),
            (false, "領収書明細", "IsRyosyuDetail"),
            (false, "主治医", "PrimaryDoctor"),
            (false, "テスト患者区分", "IsTester"),
            (false, "患者登録日時", "CreateDate"),
            (false, "最終来院日", "LastVisitDate"),
            (false, "患者コメント", "PtCmt"),
            (false, "調整額", "AdjFutan"),
            (false, "調整率", "AdjRate"),
            (false, "自動算定", "AutoSantei"),
        };

        /// <summary>
        /// 患者情報
        /// </summary>
        public static List<(bool isSelected, string outputColumnName, string saveName)> PtInfConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (true, "患者番号", "PtNum"),
            (true, "氏名", "PtName"),
            (true, "カナ氏名", "KanaName"),
            (true, "性別", "Sex"),
            (false, "生年月日(西暦)", "Birthday"),
            (false, "生年月日(和暦)", "BirthdayW"),
            (true, "生年月日(和暦西暦)", "BirthdayWS"),
            (true, "年齢", "Age"),
            (false, "年齢（月）", "AgeMonth"),
            (false, "死亡日", "DeathDate"),
            (true, "郵便番号", "HomePost"),
            (true, "住所", "HomeAddress"),
            (false, "住所１", "HomeAddress1"),
            (false, "住所２", "HomeAddress2"),
            (true, "電話番号", "Tel"),
            (false, "電話番号１", "Tel1"),
            (false, "電話番号２", "Tel2"),
            (false, "メールアドレス", "Mail"),
            (false, "世帯主名", "Setainusi"),
            (false, "世帯主との続柄", "Zokugara"),
            (false, "職業", "Job"),
            (false, "連絡先名称", "RenrakuName"),
            (false, "連絡先郵便番号", "RenrakuPost"),
            (false, "連絡先住所１", "RenrakuAddress1"),
            (false, "連絡先住所２", "RenrakuAddress2"),
            (false, "連絡先電話番号", "RenrakuTel"),
            (false, "連絡先備考", "RenrakuMemo"),
            (false, "勤務先名称", "OfficeName"),
            (false, "勤務先郵便番号", "OfficePost"),
            (false, "勤務先住所１", "OfficeAddress1"),
            (false, "勤務先住所２", "OfficeAddress2"),
            (false, "勤務先電話番号", "OfficeTel"),
            (false, "勤務先備考", "OfficeMemo"),
            (false, "領収書明細", "IsRyosyuDetail"),
            (false, "主治医", "PrimaryDoctor"),
            (false, "テスト患者区分", "IsTester"),
            (false, "患者登録日時", "CreateDate"),
            (false, "初回来院日", "FirstVisitDate"),
            (true, "最終来院日", "LastVisitDate"),
            (false, "患者コメント", "PtCmt"),
            (false, "調整額", "AdjFutan"),
            (false, "調整率", "AdjRate"),
            (false, "自動算定", "AutoSantei"),
        };

        /// <summary>
        /// 保険情報
        /// </summary>
        public static List<(bool isSelected, string outputColumnName, string saveName)> HokenInfConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (true, "患者番号", "PtNum"),
            (true, "氏名", "PtName"),
            (true, "保険組合せID", "HokenPid"),
            (true, "保険区分", "HokenKbn"),
            (true, "保険区分名称", "HokenKbnName"),
            (true, "保険種別コード", "HokenSbtCd"),
            (true, "保険種別コード名称", "HokenSbtCdName"),
            (true, "保険メモ", "HokenMemo"),
            (true, "適用開始日", "StartDate"),
            (true, "適用終了日", "EndDate"),
            (true, "保険ID", "HokenId"),
            (false, "保険番号", "HokenNo"),
            (false, "保険番号枝番", "HokenEdaNo"),
            (true, "保険者番号", "HokensyaNo"),
            (true, "記号", "Kigo"),
            (true, "番号", "Bango"),
            (true, "枝番", "EdaNo"),
            (true, "本人家族区分", "HonkeKbn"),
            (true, "法別番号", "Houbetu"),
            (false, "被保険者名", "HokensyaName"),
            (false, "被保険者郵便番号", "HokensyaPost"),
            (false, "被保険者住所", "HokensyaAddress"),
            (false, "被保険者電話番号", "HokensyaTel"),
            (false, "継続区分", "KeizokuKbn"),
            (true, "資格取得日", "SikakuDate"),
            (true, "交付日", "KofuDate"),
            (true, "高額療養費区分", "KogakuKbn"),
            (false, "高額療養費処理区分", "KogakuType"),
            (false, "限度額特例対象年月１", "TokureiYm1"),
            (false, "限度額特例対象年月２", "TokureiYm2"),
            (false, "多数回該当適用開始年月", "TasukaiYm"),
            (true, "職務上区分", "SyokumuKbn"),
            (true, "国保減免区分", "GenmenKbn"),
            (true, "国保減免割合", "GenmenRate"),
            (true, "国保減免金額", "GenmenGaku"),
            (true, "特記事項１", "Tokki1"),
            (true, "特記事項２", "Tokki2"),
            (true, "特記事項３", "Tokki3"),
            (true, "特記事項４", "Tokki4"),
            (true, "特記事項５", "Tokki5"),
            (true, "労災交付番号", "RousaiKofuNo"),
            (true, "労災災害区分", "RousaiSaigaiKbn"),
            (true, "労災事業所名", "RousaiJigyosyoName"),
            (true, "労災都道府県名", "RousaiPrefName"),
            (true, "労災所在地郡市区名", "RousaiCityName"),
            (true, "労災傷病年月日", "RousaiSyobyoDate"),
            (true, "労災傷病コード", "RousaiSyobyoCd"),
            (true, "労災労働局コード", "RousaiRoudouCd"),
            (true, "労災監督署コード", "RousaiKantokuCd"),
            (true, "労災レセ請求回数", "RousaiReceCount"),
            (true, "労災療養開始日", "RyoyoStartDate"),
            (true, "労災療養終了日", "RyoyoEndDate"),
            (true, "自賠保険会社名", "JibaiHokenName"),
            (true, "自賠保険担当者", "JibaiHokenTanto"),
            (true, "自賠保険連絡先", "JibaiHokenTel"),
            (true, "自賠受傷日", "JibaiJyusyouDate"),
            (true, "公費１ID", "Kohi1Id"),
            (false, "公費１都道府県番号", "Kohi1PrefNo"),
            (false, "公費１保険番号", "Kohi1HokenNo"),
            (false, "公費１保険番号枝番", "Kohi1HokenEdaNo"),
            (true, "公費１負担者番号", "Kohi1FutansyaNo"),
            (true, "公費１受給者番号", "Kohi1JyukyusyaNo"),
            (true, "公費１特殊受給者番号", "Kohi1TokusyuNo"),
            (true, "公費１資格取得日", "Kohi1SikakuDate"),
            (true, "公費１交付日", "Kohi1KofuDate"),
            (true, "公費１適用開始日", "Kohi1StartDate"),
            (true, "公費１適用終了日", "Kohi1EndDate"),
            (false, "公費１負担率", "Kohi1Rate"),
            (false, "公費１一部負担限度額", "Kohi1GendoGaku"),
            (true, "公費２ID", "Kohi2Id"),
            (false, "公費２都道府県番号", "Kohi2PrefNo"),
            (false, "公費２保険番号", "Kohi2HokenNo"),
            (false, "公費２保険番号枝番", "Kohi2HokenEdaNo"),
            (true, "公費２負担者番号", "Kohi2FutansyaNo"),
            (true, "公費２受給者番号", "Kohi2JyukyusyaNo"),
            (true, "公費２特殊受給者番号", "Kohi2TokusyuNo"),
            (true, "公費２資格取得日", "Kohi2SikakuDate"),
            (true, "公費２交付日", "Kohi2KofuDate"),
            (true, "公費２適用開始日", "Kohi2StartDate"),
            (true, "公費２適用終了日", "Kohi2EndDate"),
            (false, "公費２負担率", "Kohi2Rate"),
            (false, "公費２一部負担限度額", "Kohi2GendoGaku"),
            (true, "公費３ID", "Kohi3Id"),
            (false, "公費３都道府県番号", "Kohi3PrefNo"),
            (false, "公費３保険番号", "Kohi3HokenNo"),
            (false, "公費３保険番号枝番", "Kohi3HokenEdaNo"),
            (true, "公費３負担者番号", "Kohi3FutansyaNo"),
            (true, "公費３受給者番号", "Kohi3JyukyusyaNo"),
            (true, "公費３特殊受給者番号", "Kohi3TokusyuNo"),
            (true, "公費３資格取得日", "Kohi3SikakuDate"),
            (true, "公費３交付日", "Kohi3KofuDate"),
            (true, "公費３適用開始日", "Kohi3StartDate"),
            (true, "公費３適用終了日", "Kohi3EndDate"),
            (false, "公費３負担率", "Kohi3Rate"),
            (false, "公費３一部負担限度額", "Kohi3GendoGaku"),
            (true, "公費４ID", "Kohi4Id"),
            (false, "公費４都道府県番号", "Kohi4PrefNo"),
            (false, "公費４保険番号", "Kohi4HokenNo"),
            (false, "公費４保険番号枝番", "Kohi4HokenEdaNo"),
            (true, "公費４負担者番号", "Kohi4FutansyaNo"),
            (true, "公費４受給者番号", "Kohi4JyukyusyaNo"),
            (true, "公費４特殊受給者番号", "Kohi4TokusyuNo"),
            (true, "公費４資格取得日", "Kohi4SikakuDate"),
            (true, "公費４交付日", "Kohi4KofuDate"),
            (true, "公費４適用開始日", "Kohi4StartDate"),
            (true, "公費４適用終了日", "Kohi4EndDate"),
            (false, "公費４負担率", "Kohi4Rate"),
            (false, "公費４一部負担限度額", "Kohi4GendoGaku"),
        };

        /// <summary>
        /// 病名情報
        /// </summary>
        public static List<(bool isSelected, string outputColumnName, string saveName)> ByomeiInfConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (true, "患者番号", "PtNum"),
            (true, "氏名", "PtName"),
            (false, "基本病名コード", "ByomeiCd"),
            (false, "修飾語コード１", "SyusyokuCd1"),
            (false, "修飾語コード２", "SyusyokuCd2"),
            (false, "修飾語コード３", "SyusyokuCd3"),
            (false, "修飾語コード４", "SyusyokuCd4"),
            (false, "修飾語コード５", "SyusyokuCd5"),
            (false, "修飾語コード６", "SyusyokuCd6"),
            (false, "修飾語コード７", "SyusyokuCd7"),
            (false, "修飾語コード８", "SyusyokuCd8"),
            (false, "修飾語コード９", "SyusyokuCd9"),
            (false, "修飾語コード１０", "SyusyokuCd10"),
            (false, "修飾語コード１１", "SyusyokuCd11"),
            (false, "修飾語コード１２", "SyusyokuCd12"),
            (false, "修飾語コード１３", "SyusyokuCd13"),
            (false, "修飾語コード１４", "SyusyokuCd14"),
            (false, "修飾語コード１５", "SyusyokuCd15"),
            (false, "修飾語コード１６", "SyusyokuCd16"),
            (false, "修飾語コード１７", "SyusyokuCd17"),
            (false, "修飾語コード１８", "SyusyokuCd18"),
            (false, "修飾語コード１９", "SyusyokuCd19"),
            (false, "修飾語コード２０", "SyusyokuCd20"),
            (false, "修飾語コード２１", "SyusyokuCd21"),
            (true, "病名", "Byomei"),
            (true, "開始日", "StartDate"),
            (true, "転帰区分", "TenkiKbn"),
            (true, "転帰日", "TenkiDate"),
            (true, "主病名区分", "SyubyoKbn"),
            (false, "慢性疾患区分", "SikkanKbn"),
            (true, "慢性疾患区分名称", "SikkanKbnName"),
            (false, "難病外来コード", "NanbyoCd"),
            (true, "補足コメント", "HosokuCmt"),
            (true, "保険レセプトID", "HokenRid"),
            (false, "当月病名区分", "TogetuByomei"),
            (false, "レセプト非表示区分", "IsNodspRece"),
            (false, "カルテ非表示区分", "IsNodspKarte"),
        };

        /// <summary>
        /// 来院情報
        /// </summary>
        public static List<(bool isSelected, string outputColumnName, string saveName)> RaiinInfConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (true, "患者番号", "PtNum"),
            (true, "氏名", "PtName"),
            (false, "年齢（月）", "AgeMonth"),
            (true, "診療日", "SinDate"),
            (false, "来院番号", "RaiinNo"),
            (false, "親来院番号", "OyaRaiinNo"),
            (true, "状態", "Status"),
            (false, "予約フラグ", "IsYoyaku"),
            (true, "予約時間", "YoyakuTime"),
            (false, "予約者ID", "YoyakuId"),
            (false, "受付種別", "UketukeSbt"),
            (true, "受付時間", "UketukeTime"),
            (false, "受付者ID", "UketukeId"),
            (true, "受付番号", "UketukeNo"),
            (true, "診察開始時間", "SinStartTime"),
            (false, "診察終了時間", "SinEndTime"),
            (true, "精算時間", "KaikeiTime"),
            (false, "精算者ID", "KaikeiId"),
            (true, "診療科", "KaName"),
            (true, "担当医ID", "TantoId"),
            (false, "担当医", "TantoName"),
            (false, "保険組合せID", "HokenPid"),
            (true, "初再診区分", "SyosaisinKbn"),
            (false, "初再診区分略称", "SyosaisinKbnS"),
            (true, "時間枠区分", "JikanKbn"),
            (false, "来院コメント", "RaiinCmt"),
            (false, "来院備考", "RaiinBiko"),
            (false, "初回来院日フラグ", "IsFirstVisitDate"),
            (false, "初回来院日", "FirstVisitDate"),
        };

        /// <summary>
        /// 診療情報（オーダー）
        /// </summary>
        public static List<(bool isSelected, string outputColumnName, string saveName)> MedicalInfOrderConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (true, "患者番号", "PtNum"),
            (true, "氏名", "PtName"),
            (true, "診療日", "SinDate"),
            (true, "来院番号", "RaiinNo"),
            (false, "親来院番号", "OyaRaiinNo"),
            (true, "状態", "Status"),
            (false, "受付種別", "UketukeSbt"),
            (false, "診療科", "KaName"),
            (false, "担当医ID", "TantoId"),
            (false, "担当医", "TantoName"),
            (false, "受付番号", "UketukeNo"),
            (true, "並び順", "SortNo"),
            (true, "剤番号", "RpNo"),
            (true, "剤枝番", "RpEdaNo"),
            (true, "保険組合せID", "HokenPid"),
            (false, "保険組合せ名称", "HokenPname"),
            (true, "オーダー行為区分", "OdrKouiKbn"),
            (true, "剤名称", "RpName"),
            (true, "院内院外区分", "InoutKbn"),
            (true, "至急区分", "SikyuKbn"),
            (true, "処方種別", "SyohoSbt"),
            (true, "算定区分", "SanteiKbn"),
            (true, "透析区分", "TosekiKbn"),
            (true, "日数回数", "DaysCnt"),
            (true, "行番号", "RowNo"),
            (true, "診療行為区分", "SinKouiKbn"),
            (true, "診療行為コード", "ItemCd"),
            (true, "診療行為名称", "ItemName"),
            (true, "数量", "Suryo"),
            (true, "単位名称", "UnitName"),
            (false, "単位種別", "UnitSBT"),
            (false, "単位換算値", "TermVal"),
            (true, "後発医薬品区分", "KohatuKbn"),
            (true, "処方せん記載区分", "SyohoKbn"),
            (true, "処方せん記載制限区分", "SyohoLimitKbn"),
            (false, "薬剤区分", "DrugKbn"),
            (false, "用法区分", "YohoKbn"),
            (false, "告示等識別区分（１）", "Kokuji1"),
            (false, "告示等識別区分（２）", "Kokuji2"),
            (true, "レセ非表示区分", "IsNodspRece"),
            (false, "一般名コード", "IpnCd"),
            (false, "一般名", "IpnName"),
            (false, "実施区分", "JissiKbn"),
            (false, "実施日時", "JissiDate"),
            (false, "実施者", "JissiId"),
            (false, "実施端末", "JissiMachine"),
            (false, "検査依頼コード", "ReqCd"),
            (false, "分割調剤", "Bunkatu"),
            (false, "コメント名称", "CmtName"),
            (false, "コメント文", "CmtOpt"),
            (false, "文字色", "FontColor"),
        };

        /// <summary>
        /// 診療情報（算定）
        /// </summary>
        public static List<(bool isSelected, string outputColumnName, string saveName)> MedicalInfCalConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (true, "患者番号", "PtNum"),
            (true, "氏名", "PtName"),
            (true, "診療日", "SinDate"),
            (true, "来院番号", "RaiinNo"),
            (false, "親来院番号", "OyaRaiinNo"),
            (false, "状態", "Status"),
            (false, "受付種別", "UketukeSbt"),
            (false, "診療科", "KaName"),
            (false, "担当医ID", "TantoId"),
            (false, "担当医", "TantoName"),
            (false, "受付番号", "UketukeNo"),
            (true, "診療識別", "SinId"),
            (true, "剤番号", "RpNo"),
            (true, "連番", "SeqNo"),
            (true, "行番号", "RowNo"),
            (true, "算定区分", "SanteiKbn"),
            (true, "保険組合せID", "HokenPid"),
            (true, "保険ID", "HokenId"),
            (true, "点数小計", "SubTotalTen"),
            (true, "内税小計", "SubTotalZei"),
            (true, "回数小計", "SubTotalCount"),
            (true, "診療行為コード", "ItemCd"),
            (true, "オーダー診療行為コード", "OdrItemCd"),
            (true, "診療行為名称", "ItemName"),
            (true, "数量", "Suryo"),
            (true, "単位名称", "UnitName"),
            (true, "点数", "Ten"),
            (true, "内税", "Zei"),
            (true, "レセ非表示区分", "IsNodspRece"),
            (true, "紙レセ非表示区分", "IsNodspPaperRece"),
            (true, "領収証非表示区分", "IsNodspRyosyu"),
            (true, "院外処方区分", "InoutKbn"),
            (true, "円点区分", "EntenKbn"),
            (true, "自費種別", "JihiSbt"),
            (true, "課税区分", "KazeiKbn"),
        };

        /// <summary>
        /// カルテ情報
        /// </summary>
        public static List<(bool isSelected, string outputColumnName, string saveName)> MedicalRecordInfConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (true, "患者番号", "PtNum"),
            (true, "氏名", "PtName"),
            (true, "診療日", "SinDate"),
            (true, "来院番号", "RaiinNo"),
            (false, "親来院番号", "OyaRaiinNo"),
            (false, "状態", "Status"),
            (false, "受付種別", "UketukeSbt"),
            (false, "診療科", "KaName"),
            (false, "担当医ID", "TantoId"),
            (false, "担当医", "TantoName"),
            (false, "受付番号", "UketukeNo"),
            (true, "カルテ区分", "KarteKbn"),
            (true, "テキスト", "Text"),
        };

        /// <summary>
        /// 検査情報
        /// </summary>
        public static List<(bool isSelected, string outputColumnName, string saveName)> KensaInfConfig = new List<(bool isSelected, string outputColumnName, string saveName)>()
        {
            (true, "患者番号", "PtNum"),
            (true, "氏名", "PtName"),
            (true, "依頼日", "IraiDate"),
            (true, "センターコード", "CenterCd"),
            (true, "検査項目コード", "KensaItemCd"),
            (true, "検査項目名称", "KensaName"),
            (true, "結果値", "ResultValue"),
            (true, "単位名称", "UnitName"),
            (true, "基準値", "StandardVal"),
            (true, "異常値区分", "AbnormalKbn"),
        };
    }
}
