using UseCase.Core.Sync.Core;

namespace UseCase.Online.GetListOnlineConfirmationHistoryModel;

public interface IGetListOnlineConfirmationHistoryModelInputPort : IInputPort<GetListOnlineConfirmationHistoryModelInputData, GetListOnlineConfirmationHistoryModelOutputData>
{
}
