namespace AWSSDK.Constants
{
    public static class QueryConstant
    {
        public static string CreateAuditLog = @"CREATE TABLE public.""AuditLogs"" (
    ""LogId"" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" int4 NOT NULL,
    ""Domain"" text NOT NULL,
    ""ThreadId"" text NOT NULL,
    ""LogType"" text NOT NULL,
    ""HpId"" int4 NOT NULL,
    ""UserId"" int4 NOT NULL,
    ""LoginKey"" text NOT NULL,
    ""DepartmentId"" int4 NOT NULL,
    ""LogDate"" timestamptz NOT NULL,
    ""EventCd"" text NULL,
    ""PtId"" int8 NOT NULL,
    ""SinDay"" int4 NOT NULL,
    ""RaiinNo"" int8 NOT NULL,
    ""Path"" text NULL,
    ""RequestInfo"" text NOT NULL,
    ""ClientIP"" text NOT NULL,
    ""Desciption"" text NOT NULL,
    CONSTRAINT Auditlog_pk PRIMARY KEY (""LogId"", ""TenantId"")
) PARTITION BY LIST(""TenantId"");

CREATE INDEX idx_clientip on ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, (""ClientIP"")::text));
CREATE INDEX idx_desciption on ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, (""Desciption"")::text));
CREATE INDEX idx_domain ON ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, (""Domain"")::text));
CREATE INDEX idx_eventcd on ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, (""EventCd"")::text));
CREATE INDEX idx_loginkey ON ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, (""LoginKey"")::text));
CREATE INDEX idx_path on ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, (""Path"")::text));
CREATE INDEX idx_requestinfo on ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, ""RequestInfo""));
CREATE INDEX idx_threadid on ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, (""ThreadId"")::text));
CREATE INDEX idx_AuditLogslogtype on ONLY public.""AuditLogs"" USING gin (to_tsvector('english'::regconfig, (""LogType"")::text));
CREATE INDEX ""idx_AuditLogs_TenantId"" ON ONLY public.""AuditLogs"" USING btree (""TenantId"");
CREATE INDEX ""idx_AuditLogs_LogDate"" ON ONLY public.""AuditLogs"" USING btree (""LogDate"");
CREATE INDEX ""idx_AuditLogs_LogId"" ON ONLY public.""AuditLogs"" USING btree (""LogId"");
CREATE INDEX ""idx_AuditLogs_PtId"" ON ONLY public.""AuditLogs"" USING btree (""RaiinNo"");";

        public static string SqlUserPermission = @"
                    INSERT INTO public.""USER_PERMISSION""
                    (""HP_ID"", ""USER_ID"", ""FUNCTION_CD"", ""PERMISSION"", ""CREATE_DATE"", ""CREATE_ID"", ""CREATE_MACHINE"", ""UPDATE_DATE"", ""UPDATE_ID"", ""UPDATE_MACHINE"")
                    VALUES
                    (1, 1, '99201001', 0, '2021-05-30 01:23:14.067', 0, NULL, '2021-05-30 01:23:14.067', 0, NULL),
                    (1, 1, '99201002', 0, '2021-05-30 01:23:14.067', 0, NULL, '2021-05-30 01:23:14.067', 0, NULL),
                    (1, 1, '99201004', 0, '2021-05-30 01:23:14.068', 0, NULL, '2021-05-30 01:23:14.068', 0, NULL),
                    (1, 1, '99201005', 0, '2021-05-30 01:23:14.068', 0, NULL, '2021-05-30 01:23:14.068', 0, NULL),
                    (1, 1, '99201006', 0, '2021-05-30 01:23:14.068', 0, NULL, '2021-05-30 01:23:14.068', 0, NULL),
                    (1, 1, '99201007', 0, '2021-05-30 01:23:14.069', 0, NULL, '2021-05-30 01:23:14.069', 0, NULL),
                    (1, 1, '99201008', 0, '2021-05-30 01:23:14.069', 0, NULL, '2021-05-30 01:23:14.069', 0, NULL),
                    (1, 1, '99201009', 0, '2021-05-30 01:23:14.069', 0, NULL, '2021-05-30 01:23:14.069', 0, NULL),
                    (1, 1, '99201010', 0, '2021-05-30 01:23:14.070', 0, NULL, '2021-05-30 01:23:14.070', 0, NULL),
                    (1, 1, '99201011', 0, '2021-05-30 01:23:14.070', 0, NULL, '2021-05-30 01:23:14.070', 0, NULL),
                    (1, 1, '99201012', 0, '2021-05-30 01:23:14.071', 0, NULL, '2021-05-30 01:23:14.071', 0, NULL),
                    (1, 1, '99202000', 0, '2021-05-30 01:23:14.071', 0, NULL, '2021-05-30 01:23:14.071', 0, NULL),
                    (1, 1, '99203000', 0, '2021-05-30 01:23:14.072', 0, NULL, '2021-05-30 01:23:14.072', 0, NULL),
                    (1, 1, '99204000', 1, '2021-05-30 01:23:14.072', 0, NULL, '2021-05-30 01:23:14.072', 0, NULL),
                    (1, 1, '99205000', 0, '2021-05-30 01:23:14.072', 0, NULL, '2021-05-30 01:23:14.072', 0, NULL),
                    (1, 1, '99206000', 0, '2021-05-30 01:23:14.073', 0, NULL, '2021-05-30 01:23:14.073', 0, NULL),
                    (1, 1, '97101000', 0, '2021-05-30 01:23:14.075', 0, NULL, '2021-05-30 01:23:14.075', 0, NULL),
                    (1, 1, '97102000', 0, '2021-05-30 01:23:14.076', 0, NULL, '2021-05-30 01:23:14.076', 0, NULL),
                    (1, 1, '97110000', 0, '2021-05-30 01:23:14.076', 0, NULL, '2021-05-30 01:23:14.076', 0, NULL),
                    (1, 1, '97201000', 0, '2021-05-30 01:23:14.077', 0, NULL, '2021-05-30 01:23:14.077', 0, NULL),
                    (1, 1, '97202000', 0, '2021-05-30 01:23:14.078', 0, NULL, '2021-05-30 01:23:14.078', 0, NULL),
                    (1, 1, '97203000', 0, '2021-05-30 01:23:14.079', 0, NULL, '2021-05-30 01:23:14.079', 0, NULL),
                    (1, 1, '97210000', 0, '2021-05-30 01:23:14.080', 0, NULL, '2021-05-30 01:23:14.080', 0, NULL),
                    (1, 1, '97211000', 0, '2021-05-30 01:23:14.081', 0, NULL, '2021-05-30 01:23:14.081', 0, NULL),
                    (1, 1, '97220000', 0, '2021-05-30 01:23:14.081', 0, NULL, '2021-05-30 01:23:14.081', 0, NULL),
                    (1, 1, '97900000', 0, '2021-05-30 01:23:14.082', 0, NULL, '2021-05-30 01:23:14.082', 0, NULL),
                    (1, 1, '99013000', 0, '2021-05-30 01:23:14.065', 0, NULL, '2021-05-30 01:23:14.065', 0, NULL),
                    (1, 1, '99201003', 0, '2021-05-30 01:23:14.067', 0, NULL, '2023-11-22 10:42:59.113', 1, 'CATNROSE'),
                    (1, 1, '97221000', 0, '2023-08-19 22:02:10.821', 2, '', '2023-08-19 22:02:10.864', 2, ''),
                    (1, 1, '97301000', 0, '2023-08-19 22:02:13.483', 2, '', '2023-08-19 22:02:13.483', 2, ''),
                    (1, 1, '97310000', 0, '2023-08-19 22:02:13.486', 2, '', '2023-08-19 22:02:13.486', 2, ''),
                    (1, 1, '97320000', 0, '2023-08-19 22:02:13.488', 2, '', '2023-08-19 22:02:13.488', 2, ''),
                    (1, 1, '97330000', 0, '2023-08-19 22:02:13.490', 2, '', '2023-08-19 22:02:13.490', 2, ''),
                    (1, 1, '97340000', 0, '2023-08-19 22:02:13.492', 2, '', '2023-08-19 22:02:13.492', 2, ''),
                    (1, 1, '97341000', 0, '2023-08-19 22:02:13.494', 2, '', '2023-08-19 22:02:13.494', 2, ''),
                    (1, 1, '97350000', 0, '2023-08-19 22:02:13.496', 2, '', '2023-08-19 22:02:13.496', 2, ''),
                    (1, 1, '97360000', 0, '2023-08-19 22:02:13.498', 2, '', '2023-08-19 22:02:13.498', 2, ''),
                    (1, 1, '97361000', 0, '2023-08-19 22:02:13.501', 2, '', '2023-08-19 22:02:13.501', 2, ''),
                    (1, 1, '97370000', 0, '2023-08-19 22:02:13.503', 2, '', '2023-08-19 22:02:13.503', 2, ''),
                    (1, 1, '97380000', 0, '2023-08-19 22:02:13.507', 2, '', '2023-08-19 22:02:13.507', 2, ''),
                    (1, 1, '97390000', 0, '2023-08-19 22:02:13.509', 2, '', '2023-08-19 22:02:13.509', 2, ''),
                    (1, 1, '99201000', 0, '2023-08-19 22:02:13.511', 2, '', '2023-08-19 22:02:13.511', 2, ''),
                    (1, 1, '99999000', 0, '2023-08-19 22:02:13.513', 2, '', '2023-08-19 22:02:13.513', 2, ''),
                    (1, 1, '02000000', 0, '2021-05-30 01:23:14.065', 0, NULL, '2023-11-22 10:42:59.112', 1, 'CATNROSE'),
                    (1, 1, '99005000', 0, '2021-05-30 01:23:14.084', 0, NULL, '2023-11-22 10:42:59.113', 1, 'CATNROSE'),
                    (1, 1, '99201013', 0, '2021-05-30 01:23:14.071', 0, NULL, '2023-11-22 10:42:59.113', 1, 'CATNROSE'),
                    (1, 1, '02001000', 0, '2023-11-22 10:42:59.114', 1, 'CATNROSE', '2023-11-22 10:42:59.114', 1, 'CATNROSE');";
        public static string SqlUser = "INSERT INTO public.\"USER_MST\" (\"HP_ID\",\r\n\"ID\",\r\n\"USER_ID\",\r\n\"JOB_CD\",\r\n\"MANAGER_KBN\",\r\n\"KA_ID\",\r\n\"KANA_NAME\",\r\n\"NAME\",\r\n\"SNAME\",\r\n\"LOGIN_ID\",\r\n\"LOGIN_PASS\",\r\n\"MAYAKU_LICENSE_NO\",\r\n\"START_DATE\",\r\n\"END_DATE\",\r\n\"SORT_NO\",\r\n\"IS_DELETED\",\r\n\"CREATE_DATE\",\r\n\"CREATE_ID\",\r\n\"CREATE_MACHINE\",\r\n\"UPDATE_DATE\",\r\n\"UPDATE_ID\",\r\n\"UPDATE_MACHINE\",\r\n\"RENKEI_CD1\",\r\n\"DR_NAME\",\r\n\"LOGIN_TYPE\",\r\n\"HPKI_SN\",\r\n\"HPKI_ISSUER_DN\")\r\nVALUES(1, 0, 1001, 1, 7, 1, '', '', '', '{0}', '{1}', '', 0, 99999999, 0, 0, '2004-01-10 00:00:00.000', 0, NULL, '2023-10-10 00:11:18.558', 0, '', '', '', 0, NULL, NULL);";

        public static string SaveSystemChangeLog = "INSERT INTO public.\"SYSTEM_CHANGE_LOG\" (\"FILE_NAME\",\"IS_PG\",\"IS_DB\",\"IS_MASTER\",\"IS_NOTE\",\"STATUS\",\"ERR_MESSAGE\",\"CREATE_DATE\",\"UPDATE_DATE\",\"IS_RUN\",\"IS_DRUG_PHOTO\")\r\n\tVALUES (@FileName, @IsPG, @IsDB, @IsMaster, @IsNote, @Status, @ErrMessage, @CreateDate, @UpdateDate, @IsRun, @IsDrugPhoto);\r\n";

        public static string RenameTableNames = @"
            CREATE OR REPLACE FUNCTION public.rename_table_names()
             RETURNS void
             LANGUAGE plpgsql
            AS $function$
            DECLARE 
                table_name_var text;  
                exec_query text; 
            BEGIN
                FOR table_name_var IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' and table_name not like '%partition%') 
                LOOP
                    exec_query := 'ALTER TABLE ""' || table_name_var || '"" RENAME TO ""' || lower(table_name_var) || '"";';
                    EXECUTE exec_query;
                END LOOP;
            END $function$
            ;

            SELECT rename_table_names();
        ";

        public static string RenameFieldNames =
            "CREATE OR REPLACE FUNCTION public.rename_field_names()" +
            " RETURNS void" +
            " LANGUAGE plpgsql" +
            " AS $function$" +
            " DECLARE " +
            "     table_name_var text;  " +
            "     column_name_var text;" +
            "     exec_query text;   " +
            " BEGIN" +
            "     FOR table_name_var IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' and table_name not like '%partition%')" +
            "     LOOP" +
            "         FOR column_name_var IN (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = table_name_var)" +
            "         LOOP " +
            "             exec_query := " +
            "                 'ALTER TABLE \"' || lower(table_name_var) || " +
            "                 '\" RENAME COLUMN \"' || column_name_var || " +
            "                 '\" TO \"' || lower(column_name_var) || '\";';" +
            "             EXECUTE exec_query;" +
            "         END LOOP;" +
            "     END LOOP;" +
            " END $function$" +
            " ;" +
            " SELECT rename_field_names();";
    }
}
