using Domain.Models.PtCmtInf;
using Domain.Models.PtInfection;
using Domain.Models.TenMst;
using Entity.Tenant;
using Helper.Constants;
using Infrastructure.Interfaces;
using PostgreDataContext;

namespace Infrastructure.Repositories;

public class TenMstRepository : ITenMstRepository
{
    private readonly TenantDataContext _tenantDataContext;

    public TenMstRepository(ITenantProvider tenantProvider)
    {
        _tenantDataContext = tenantProvider.GetTrackingTenantDataContext();
    }

    public List<TenMstModel> GetList(int hpId, int sinDate)
    {
        var tenMsts = _tenantDataContext.TenMsts.Where(x => x.HpId == hpId && x.StartDate <= sinDate && x.EndDate >= sinDate).ToList();
        return tenMsts.Select(x => ConvertToModel(x)).ToList();
    }

    private TenMstModel ConvertToModel(TenMst itemData)
    {
        return new TenMstModel(
                itemData.HpId,
                itemData.ItemCd,
                itemData.StartDate,
                itemData.EndDate,
                itemData.MasterSbt ?? String.Empty,
                itemData.SinKouiKbn,
                itemData.Name ?? String.Empty,
                itemData.KanaName1 ?? String.Empty,
                itemData.KanaName2 ?? String.Empty,
                itemData.KanaName3 ?? String.Empty,
                itemData.KanaName4 ?? String.Empty,
                itemData.KanaName5 ?? String.Empty,
                itemData.KanaName6 ?? String.Empty,
                itemData.KanaName7 ?? String.Empty,
                itemData.RyosyuName ?? String.Empty,
                itemData.ReceName ?? String.Empty,
                itemData.TenId,
                itemData.Ten,
                itemData.ReceUnitCd ?? String.Empty,
                itemData.ReceUnitName ?? String.Empty,
                itemData.OdrUnitName ?? String.Empty,
                itemData.CnvUnitName ?? String.Empty,
                itemData.OdrTermVal,
                itemData.CnvTermVal,
                itemData.DefaultVal,
                itemData.IsAdopted,
                itemData.KoukiKbn,
                itemData.HokatuKensa,
                itemData.ByomeiKbn,
                itemData.Igakukanri,
                itemData.JitudayCount,
                itemData.Jituday,
                itemData.DayCount,
                itemData.DrugKanrenKbn,
                itemData.KizamiId,
                itemData.KizamiMin,
                itemData.KizamiMax,
                itemData.KizamiVal,
                itemData.KizamiTen,
                itemData.KizamiErr,
                itemData.MaxCount,
                itemData.MaxCountErr,
                itemData.TyuCd ?? String.Empty,
                itemData.TyuSeq ?? String.Empty,
                itemData.TusokuAge,
                itemData.MinAge ?? String.Empty,
                itemData.MaxAge ?? String.Empty,
                itemData.TimeKasanKbn,
                itemData.FutekiKbn,
                itemData.FutekiSisetuKbn,
                itemData.SyotiNyuyojiKbn,
                itemData.LowWeightKbn,
                itemData.HandanKbn,
                itemData.HandanGrpKbn,
                itemData.TeigenKbn,
                itemData.SekituiKbn,
                itemData.KeibuKbn,
                itemData.AutoHougouKbn,
                itemData.GairaiKanriKbn,
                itemData.TusokuTargetKbn,
                itemData.HokatuKbn,
                itemData.TyoonpaNaisiKbn,
                itemData.AutoFungoKbn,
                itemData.TyoonpaGyokoKbn,
                itemData.GazoKasan,
                itemData.KansatuKbn,
                itemData.MasuiKbn,
                itemData.FukubikuNaisiKasan,
                itemData.FukubikuKotunanKasan,
                itemData.MasuiKasan,
                itemData.MoniterKasan,
                itemData.ToketuKasan ,
                itemData.TenKbnNo ?? String.Empty,
                itemData.ShortstayOpe,
                itemData.BuiKbn,
                itemData.Sisetucd1,
                itemData.Sisetucd2,
                itemData.Sisetucd3,
                itemData.Sisetucd4,
                itemData.Sisetucd5,
                itemData.Sisetucd6,
                itemData.Sisetucd7,
                itemData.Sisetucd8,
                itemData.Sisetucd9,
                itemData.Sisetucd10,
                itemData.AgekasanMin1 ?? String.Empty,
                itemData.AgekasanMax1 ?? String.Empty,
                itemData.AgekasanCd1 ?? String.Empty,
                itemData.AgekasanMin2 ?? String.Empty,
                itemData.AgekasanMax2 ?? String.Empty,
                itemData.AgekasanCd2 ?? String.Empty,
                itemData.AgekasanMin3 ?? String.Empty,
                itemData.AgekasanMax3 ?? String.Empty,
                itemData.AgekasanCd3 ?? String.Empty,
                itemData.AgekasanMin4 ?? String.Empty,
                itemData.AgekasanMax4 ?? String.Empty,
                itemData.AgekasanCd4 ?? String.Empty,
                itemData.KensaCmt,
                itemData.MadokuKbn,
                itemData.SinkeiKbn,
                itemData.SeibutuKbn,
                itemData.ZoueiKbn,
                itemData.DrugKbn,
                itemData.ZaiKbn,
                itemData.Capacity,
                itemData.KohatuKbn,
                itemData.TokuzaiAgeKbn,
                itemData.SansoKbn,
                itemData.TokuzaiSbt,
                itemData.MaxPrice,
                itemData.MaxTen,
                itemData.SyukeiSaki ?? String.Empty,
                itemData.CdKbn ?? String.Empty,
                itemData.CdSyo,
                itemData.CdBu,
                itemData.CdKbnno,
                itemData.CdEdano,
                itemData.CdKouno,
                itemData.KokujiKbn ?? String.Empty,
                itemData.KokujiSyo,
                itemData.KokujiBu,
                itemData.KokujiKbnNo,
                itemData.KokujiEdaNo,
                itemData.KokujiKouNo,
                itemData.Kokuji1 ?? String.Empty,
                itemData.Kokuji2 ?? String.Empty,
                itemData.KohyoJun,
                itemData.YjCd ?? String.Empty,
                itemData.YakkaCd ?? String.Empty,
                itemData.SyusaiSbt,
                itemData.SyohinKanren ?? String.Empty,
                itemData.UpdDate,
                itemData.DelDate,
                itemData.KeikaDate,
                itemData.RousaiKbn,
                itemData.SisiKbn,
                itemData.ShotCnt,
                itemData.IsNosearch,
                itemData.IsNodspPaperRece,
                itemData.IsNodspRece,
                itemData.IsNodspRyosyu,
                itemData.IsNodspKarte,
                itemData.JihiSbt,
                itemData.KazeiKbn,
                itemData.YohoKbn,
                itemData.IpnNameCd ?? String.Empty,
                itemData.FukuyoRise,
                itemData.FukuyoMorning,
                itemData.FukuyoDaytime,
                itemData.FukuyoNight,
                itemData.FukuyoSleep,
                itemData.SuryoRoundupKbn,
                itemData.KouseisinKbn,
                itemData.SanteiItemCd,
                itemData.SanteigaiKbn,
                itemData.KensaItemCd ?? String.Empty,
                itemData.KensaItemSeqNo,
                itemData.RenkeiCd1 ?? String.Empty,
                itemData.RenkeiCd2 ?? String.Empty,
                itemData.SaiketuKbn,
                itemData.CmtKbn,
                itemData.CmtCol1,
                itemData.CmtColKeta1,
                itemData.CmtCol2,
                itemData.CmtColKeta2,
                itemData.CmtCol3,
                itemData.CmtColKeta3,
                itemData.CmtCol4,
                itemData.CmtColKeta4,
                itemData.SelectCmtId,
                itemData.ChusyaDrugSbt,
                itemData.KensaFukusuSantei,
                itemData.AgeCheck,
                itemData.KokujiBetuno,
                itemData.KokujiKbnno,
                itemData.CmtSbt,
                itemData.IsNodspYakutai,
                itemData.ZaikeiPoint,
                itemData.KensaLabel
                
                ) ;
    }
}
