using Domain.Models.TenMstMaintenance;
using Infrastructure.Base;
using Infrastructure.Interfaces;

namespace Infrastructure.Repositories
{
    public class TenMstMaintenanceRepository : RepositoryBase, ITenMstMaintenanceRepository
    {
        public TenMstMaintenanceRepository(ITenantProvider tenantProvider) : base(tenantProvider)
        {
        }

        public List<TenMstOriginModel> GetGroupTenMst(string itemCd)
        {
            return NoTrackingDataContext.TenMsts.Where(item => item.ItemCd == itemCd)
                                                .OrderByDescending(item => item.StartDate)
                                                .Select(x => new TenMstOriginModel(x.HpId,
                                                                                   x.ItemCd,
                                                                                   x.StartDate,
                                                                                   x.EndDate,
                                                                                   x.MasterSbt ?? string.Empty,
                                                                                   x.SinKouiKbn,
                                                                                   x.Name ?? string.Empty,
                                                                                   x.KanaName1 ?? string.Empty,
                                                                                   x.KanaName2 ?? string.Empty,
                                                                                   x.KanaName3 ?? string.Empty,
                                                                                   x.KanaName4 ?? string.Empty,
                                                                                   x.KanaName5 ?? string.Empty,
                                                                                   x.KanaName6 ?? string.Empty,
                                                                                   x.KanaName7 ?? string.Empty,
                                                                                   x.RyosyuName ?? string.Empty,
                                                                                   x.ReceName ?? string.Empty,
                                                                                   x.TenId,
                                                                                   x.Ten,
                                                                                   x.ReceUnitCd ?? string.Empty,
                                                                                   x.ReceUnitName ?? string.Empty,
                                                                                   x.OdrUnitName ?? string.Empty,
                                                                                   x.CnvUnitName ?? string.Empty,
                                                                                   x.OdrTermVal,
                                                                                   x.CnvTermVal,
                                                                                   x.DefaultVal,
                                                                                   x.IsAdopted,
                                                                                   x.KoukiKbn,
                                                                                   x.HokatuKensa,
                                                                                   x.ByomeiKbn,
                                                                                   x.Igakukanri,
                                                                                   x.JitudayCount,
                                                                                   x.Jituday,
                                                                                   x.DayCount,
                                                                                   x.DrugKanrenKbn,
                                                                                   x.KizamiId,
                                                                                   x.KizamiMin,
                                                                                   x.KizamiMax,
                                                                                   x.KizamiVal,
                                                                                   x.KizamiTen,
                                                                                   x.KizamiErr,
                                                                                   x.MaxCount,
                                                                                   x.MaxCountErr,
                                                                                   x.TyuCd ?? string.Empty,
                                                                                   x.TyuSeq ?? string.Empty,
                                                                                   x.TusokuAge,
                                                                                   x.MinAge ?? string.Empty,
                                                                                   x.MaxAge ?? string.Empty,
                                                                                   x.AgeCheck,
                                                                                   x.TimeKasanKbn,
                                                                                   x.FutekiKbn,
                                                                                   x.FutekiSisetuKbn,
                                                                                   x.SyotiNyuyojiKbn,
                                                                                   x.LowWeightKbn,
                                                                                   x.HandanKbn,
                                                                                   x.HandanGrpKbn,
                                                                                   x.TeigenKbn,
                                                                                   x.SekituiKbn,
                                                                                   x.KeibuKbn,
                                                                                   x.AutoHougouKbn,
                                                                                   x.GairaiKanriKbn,
                                                                                   x.TusokuTargetKbn,
                                                                                   x.HokatuKbn,
                                                                                   x.TyoonpaNaisiKbn,
                                                                                   x.AutoFungoKbn,
                                                                                   x.TyoonpaGyokoKbn,
                                                                                   x.GazoKasan,
                                                                                   x.KansatuKbn,
                                                                                   x.MasuiKbn,
                                                                                   x.FukubikuNaisiKasan,
                                                                                   x.FukubikuKotunanKasan,
                                                                                   x.MasuiKasan,
                                                                                   x.MoniterKasan,
                                                                                   x.ToketuKasan,
                                                                                   x.TenKbnNo ?? string.Empty,
                                                                                   x.ShortstayOpe,
                                                                                   x.BuiKbn,
                                                                                   x.Sisetucd1,
                                                                                   x.Sisetucd2,
                                                                                   x.Sisetucd3,
                                                                                   x.Sisetucd4,
                                                                                   x.Sisetucd5,
                                                                                   x.Sisetucd6,
                                                                                   x.Sisetucd7,
                                                                                   x.Sisetucd8,
                                                                                   x.Sisetucd9,
                                                                                   x.Sisetucd10,
                                                                                   x.AgekasanMin1 ?? string.Empty,
                                                                                   x.AgekasanMax1 ?? string.Empty,
                                                                                   x.AgekasanCd1 ?? string.Empty,
                                                                                   x.AgekasanMin2 ?? string.Empty,
                                                                                   x.AgekasanMax2 ?? string.Empty,
                                                                                   x.AgekasanCd2 ?? string.Empty,
                                                                                   x.AgekasanMin3 ?? string.Empty,
                                                                                   x.AgekasanMax3 ?? string.Empty,
                                                                                   x.AgekasanCd3 ?? string.Empty,
                                                                                   x.AgekasanMin4 ?? string.Empty,
                                                                                   x.AgekasanMax4 ?? string.Empty,
                                                                                   x.AgekasanCd4 ?? string.Empty,
                                                                                   x.KensaCmt,
                                                                                   x.MadokuKbn,
                                                                                   x.SinkeiKbn,
                                                                                   x.SeibutuKbn,
                                                                                   x.ZoueiKbn,
                                                                                   x.DrugKbn,
                                                                                   x.ZaiKbn,
                                                                                   x.ZaikeiPoint,
                                                                                   x.Capacity,
                                                                                   x.KohatuKbn,
                                                                                   x.TokuzaiAgeKbn,
                                                                                   x.SansoKbn,
                                                                                   x.TokuzaiSbt,
                                                                                   x.MaxPrice,
                                                                                   x.MaxTen,
                                                                                   x.SyukeiSaki ?? string.Empty,
                                                                                   x.CdKbn ?? string.Empty,
                                                                                   x.CdSyo,
                                                                                   x.CdBu,
                                                                                   x.CdKbnno,
                                                                                   x.CdEdano,
                                                                                   x.CdKouno,
                                                                                   x.KokujiKbn ?? string.Empty,
                                                                                   x.KokujiSyo,
                                                                                   x.KokujiBu,
                                                                                   x.KokujiKbnNo,
                                                                                   x.KokujiEdaNo,
                                                                                   x.KokujiKouNo,
                                                                                   x.Kokuji1 ?? string.Empty,
                                                                                   x.Kokuji2 ?? string.Empty,
                                                                                   x.KohyoJun,
                                                                                   x.YjCd ?? string.Empty,
                                                                                   x.YakkaCd ?? string.Empty,
                                                                                   x.SyusaiSbt,
                                                                                   x.SyohinKanren ?? string.Empty,
                                                                                   x.UpdDate,
                                                                                   x.DelDate,
                                                                                   x.KeikaDate,
                                                                                   x.RousaiKbn,
                                                                                   x.SisiKbn,
                                                                                   x.ShotCnt,
                                                                                   x.IsNosearch,
                                                                                   x.IsNodspPaperRece,
                                                                                   x.IsNodspRece,
                                                                                   x.IsNodspRyosyu,
                                                                                   x.IsNodspKarte,
                                                                                   x.IsNodspYakutai,
                                                                                   x.JihiSbt,
                                                                                   x.KazeiKbn,
                                                                                   x.YohoKbn,
                                                                                   x.IpnNameCd ?? string.Empty,
                                                                                   x.FukuyoRise,
                                                                                   x.FukuyoMorning,
                                                                                   x.FukuyoDaytime,
                                                                                   x.FukuyoNight,
                                                                                   x.FukuyoSleep,
                                                                                   x.SuryoRoundupKbn,
                                                                                   x.KouseisinKbn,
                                                                                   x.ChusyaDrugSbt,
                                                                                   x.KensaFukusuSantei,
                                                                                   x.SanteiItemCd ?? string.Empty,
                                                                                   x.SanteigaiKbn,
                                                                                   x.KensaItemCd ?? string.Empty,
                                                                                   x.KensaItemSeqNo,
                                                                                   x.RenkeiCd1 ?? string.Empty,
                                                                                   x.RenkeiCd2 ?? string.Empty,
                                                                                   x.SaiketuKbn,
                                                                                   x.CmtKbn,
                                                                                   x.CmtCol1,
                                                                                   x.CmtColKeta1,
                                                                                   x.CmtCol2,
                                                                                   x.CmtColKeta2,
                                                                                   x.CmtCol3,
                                                                                   x.CmtColKeta3,
                                                                                   x.CmtCol4,
                                                                                   x.CmtColKeta4,
                                                                                   x.SelectCmtId,
                                                                                   x.KensaLabel,
                                                                                   false,
                                                                                   false,
                                                                                   x.IsDeleted,
                                                                                   false,
                                                                                   x.StartDate)).ToList();
        }

        public void ReleaseResource()
        {
            DisposeDataContext();
        }
    }
}
