using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UseCase.Insurance.ValidKohi
{
    public enum ValidKohiStatus: byte
    {
        InvalidFaild = 0,
        InvalidSuccess = 1,
        InvalidSindate = 2,
        InvalidPtBirthday = 3,
        InvalidKohiEmptyModel1 = 4,
        InvalidKohiHokenMstEmpty1 = 5,
        InvalidFutansyaNoEmpty1 = 6,
        InvalidJyukyusyaNo1 = 7,
        InvalidTokusyuNo1 = 8, 
        InvalidFutansyaNo01 = 9,
        InvalidKohiYukoDate1 = 10,
        InvalidKohiHokenMstStartDate1 = 11,
        InvalidKohiHokenMstEndDate1 = 12,
        InvalidKohiConfirmDate1 = 13,
        InvalidMstCheckHBT1 = 14,
        InvalidMstCheckDigitFutansyaNo1 = 15,
        InvalidMstCheckDigitJyukyusyaNo1 = 16,
        InvalidMstCheckAge1 = 17,
        InvalidFutanJyoTokuNull1 = 18,
        InvalidKohiEmptyModel2 = 19,
        InvalidKohiHokenMstEmpty2 = 20,
        InvalidFutansyaNoEmpty2 = 21,
        InvalidJyukyusyaNo2 = 22,
        InvalidTokusyuNo2 = 23,
        InvalidFutansyaNo02 = 24,
        InvalidKohiYukoDate2 = 25,
        InvalidKohiHokenMstStartDate2 = 26,
        InvalidKohiHokenMstEndDate2 = 27,
        InvalidKohiConfirmDate2 = 28,
        InvalidMstCheckHBT2 = 29,
        InvalidMstCheckDigitFutansyaNo2 = 30,
        InvalidMstCheckDigitJyukyusyaNo2 = 31,
        InvalidMstCheckAge2 = 32,
        InvalidFutanJyoTokuNull2 = 33,
        InvalidKohiEmptyModel3 = 34,
        InvalidKohiHokenMstEmpty3 = 35,
        InvalidFutansyaNoEmpty3 = 36,
        InvalidJyukyusyaNo3 = 37,
        InvalidTokusyuNo3 = 38,
        InvalidFutansyaNo03 = 39,
        InvalidKohiYukoDate3 = 40,
        InvalidKohiHokenMstStartDate3 = 41,
        InvalidKohiHokenMstEndDate3 = 42,
        InvalidKohiConfirmDate3 = 43,
        InvalidMstCheckHBT3 = 44,
        InvalidMstCheckDigitFutansyaNo3 = 45,
        InvalidMstCheckDigitJyukyusyaNo3 = 46,
        InvalidMstCheckAge3 = 47,
        InvalidFutanJyoTokuNull3 = 48,
        InvalidKohiEmptyModel4 = 49,
        InvalidKohiHokenMstEmpty4 = 50,
        InvalidFutansyaNoEmpty4 = 51,
        InvalidJyukyusyaNo4 = 52,
        InvalidTokusyuNo4 = 53,
        InvalidFutansyaNo04 = 54,
        InvalidKohiYukoDate4 = 55,
        InvalidKohiHokenMstStartDate4 = 56,
        InvalidKohiHokenMstEndDate4 = 57,
        InvalidKohiConfirmDate4 = 58,
        InvalidMstCheckHBT4 = 59,
        InvalidMstCheckDigitFutansyaNo4 = 60,
        InvalidMstCheckDigitJyukyusyaNo4 = 61,
        InvalidMstCheckAge4 = 62,
        InvalidFutanJyoTokuNull4 = 63,
        InvalidKohiEmpty21 = 64,
        InvalidKohiEmpty31 = 65,
        InvalidKohiEmpty32 = 66,
        InvalidKohiEmpty41 = 67,
        InvalidKohiEmpty42 = 68,
        InvalidKohiEmpty43 = 69,
        InvalidDuplicateKohi1 = 70,
        InvalidDuplicateKohi2 = 71,
        InvalidDuplicateKohi3 = 72,
        InvalidDuplicateKohi4 = 73
    }
}
