using UseCase.Core.Sync.Core;

namespace UseCase.PatientInfor.UpdateVisitTimesManagementNeedSave;

public interface IUpdateVisitTimesManagementNeedSaveInputPort : IInputPort<UpdateVisitTimesManagementNeedSaveInputData, UpdateVisitTimesManagementNeedSaveOutputData>
{
}
